### ISSUE TITLE
Dependency issue in windows when installing gem.

### ISSUE THREAD

**Issue by bdj61383** [youpy/ruby-echonest#3]
Installing libxml-ruby (2.3.2) with native extensions
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension
.

```
    C:/Ruby193/bin/ruby.exe extconf.rb
```

extconf.rb:17: Use RbConfig instead of obsolete and deprecated Config.
checking for socket() in -lsocket... no
checking for gethostbyname() in -lnsl... no
checking for atan() in -lm... yes
checking for inflate() in -lz... no
checking for inflate() in -lzlib... no
checking for inflate() in -lzlib1... no
checking for inflate() in -llibz... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby193/bin/ruby
        --with-iconv-dir
        --without-iconv-dir
        --with-iconv-include
        --without-iconv-include=${iconv-dir}/include
        --with-iconv-lib
        --without-iconv-lib=${iconv-dir}/lib
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-socketlib
        --without-socketlib
        --with-nsllib
        --without-nsllib
        --with-mlib
        --without-mlib
        --with-zlib
        --without-zlib
        --with-zliblib
        --without-zliblib
        --with-zlib1lib
        --without-zlib1lib
        --with-libzlib
        --without-libzlib
 extconf failure: need zlib

Gem files will remain installed in C:/Ruby193/lib/ruby/gems/1.9.1/gems/libxml-ru
by-2.3.2 for inspection.
Results logged to C:/Ruby193/lib/ruby/gems/1.9.1/gems/libxml-ruby-2.3.2/ext/libx
ml/gem_make.out
An error occured while installing libxml-ruby (2.3.2), and Bundler cannot contin
ue.
Make sure that `gem install libxml-ruby -v '2.3.2'` succeeds before bundling.

**Comment by mickfeech** [comment]
libxml-ruby will install as 2.3.0

**Comment by bdj61383** [comment]
Thank you!  Ended up buying a mac...

On Thu, Jun 7, 2012 at 8:27 AM, mickfeech <
reply@reply.github.com
